### ISSUE TITLE
suggestion: add Toggle() or Flip()

### ISSUE THREAD

**Issue by emicklei** [tevino/abool#2]
can we have an additional operation to change the value from true->false and vice versa, atomically?

**Comment by tevino** [comment]
@emicklei It would be awesome if you could make a pull request about it.

**Comment by barryz** [comment]
@emicklei @tevino  Flip() method implemented 😄

**Comment by tevino** [comment]
I'm closing this since `Toogle()` was added in [v1.1](https://github.com/tevino/abool/releases/tag/v1.1.0).
