### ISSUE TITLE
Toggle breaks SetToIf

### ISSUE THREAD

**Issue by schicho** [tevino/abool#7]
The following piece of code demonstrates the bug.
I initially added this as a test, but was then unable to solve the bug, using only one atomic function.

```go
func TestSetToIfAfterMultipleToggles(t *testing.T) {
	v := New() // false

	v.Toggle() // true
	v.Toggle() // false
	v.Toggle() // true

	// As v is true, it should now be flipped to false
	v.SetToIf(true, false)
	expected := false

	if v.IsSet() != expected {
		t.Fatalf("Toggling the value atleast 3 times, until it's true, `SetToIf(true, false)` should flip v to false, expected: %v, got %v", expected, v.IsSet())
	}
}
```

This happens, as `Toggle` just increases the int32 by +1 every time, but `SetToIf` only compares the int32 against 1 and 0 (instead of odd and even).

**Comment by tevino** [comment]
@schicho Thank you so much for reporting this issue, I just reverted related changes to mitigate the issue (https://github.com/tevino/abool/commit/fa0b8a912b4002e2c6fd37213fd25a63d963eed1) so to reduce the impact to users, meanwhile we have more time to take a thorough look at this. I'll take a look later on.

I just added the credit for you https://github.com/tevino/abool/commit/7e73116d51abdf5e715b53fc5820e6c227d37853, thanks for your work! 👍

**Comment by schicho** [comment]
I found this solution from Uber's implementation:

https://github.com/uber-go/atomic/blob/3504dfaa1fa414923b1c8693f45d2f6931daf229/bool_ext.go#L40

as both projects are MIT licensed, I think this can be copied with a note to Uber's repository.
