### ISSUE TITLE
invalid gomod for v2

### ISSUE THREAD

**Issue by aguilbau** [tevino/abool#9]
The command `go mod download github.com/tevino/abool/v2` fails with the following error :

```
go: github.com/tevino/abool/v2@v2.0.0: go.mod has non-.../v2 module path "github.com/tevino/abool" (and .../v2/go.mod does not exist) at revision v2.0.0
```

**Comment by tevino** [comment]
@aguilbau I just updated v2.0.1 https://github.com/tevino/abool/commit/7170548ea79668d7ddede5b7f1ed726a79c59df1, could you try it again?

`go get github.com/tevino/abool/v2` works for me.

Thanks for the feedback.
